// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SpaceXProductManagerApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241019061815_UpdateComponentDependencies")]
    partial class UpdateComponentDependencies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("ComponentImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SpacecraftId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpacecraftId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("ComponentDependency", b =>
                {
                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<int>("DependencyId")
                        .HasColumnType("int");

                    b.HasKey("ComponentId", "DependencyId");

                    b.HasIndex("DependencyId");

                    b.ToTable("ComponentDependencies");
                });

            modelBuilder.Entity("Spacecraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("SpaceCraftImage")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Spacecrafts");
                });

            modelBuilder.Entity("Component", b =>
                {
                    b.HasOne("Spacecraft", null)
                        .WithMany("Components")
                        .HasForeignKey("SpacecraftId");
                });

            modelBuilder.Entity("ComponentDependency", b =>
                {
                    b.HasOne("Component", "Component")
                        .WithMany("ComponentDependencies")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Component", "Dependency")
                        .WithMany("DependentOn")
                        .HasForeignKey("DependencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Dependency");
                });

            modelBuilder.Entity("Component", b =>
                {
                    b.Navigation("ComponentDependencies");

                    b.Navigation("DependentOn");
                });

            modelBuilder.Entity("Spacecraft", b =>
                {
                    b.Navigation("Components");
                });
#pragma warning restore 612, 618
        }
    }
}
